# Generated by Django 4.1.11 on 2026-02-04 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contabilidade', '0002_add_cnae_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanalWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome identificador do canal', max_length=100, verbose_name='nome')),
                ('instance_name', models.CharField(help_text='Nome único da instância na Evolution API', max_length=100, unique=True, verbose_name='nome da instância')),
                ('instance_id', models.CharField(blank=True, help_text='ID retornado pela Evolution API', max_length=100, verbose_name='ID da instância')),
                ('webhook_url', models.URLField(blank=True, help_text='URL configurada para receber eventos', verbose_name='URL do webhook')),
                ('status', models.CharField(choices=[('disconnected', 'Desconectado'), ('connecting', 'Conectando'), ('connected', 'Conectado'), ('qrcode', 'Aguardando QR Code')], default='disconnected', max_length=20, verbose_name='status')),
                ('phone_number', models.CharField(blank=True, help_text='Número do WhatsApp conectado', max_length=20, verbose_name='número conectado')),
                ('qrcode_base64', models.TextField(blank=True, help_text='QR Code em base64 para conexão', verbose_name='QR Code')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('contabilidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canais_whatsapp', to='contabilidade.contabilidade', verbose_name='contabilidade')),
            ],
            options={
                'verbose_name': 'canal WhatsApp',
                'verbose_name_plural': 'canais WhatsApp',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(help_text='Tipo do evento recebido (messages.upsert, connection.update, etc)', max_length=50, verbose_name='tipo do evento')),
                ('instance_name', models.CharField(blank=True, max_length=100, verbose_name='nome da instância')),
                ('payload', models.JSONField(help_text='Payload completo do webhook', verbose_name='payload')),
                ('processed', models.BooleanField(default=False, help_text='Se o evento foi processado com sucesso', verbose_name='processado')),
                ('error_message', models.TextField(blank=True, help_text='Erro ocorrido durante processamento', verbose_name='mensagem de erro')),
                ('phone_from', models.CharField(blank=True, max_length=20, verbose_name='telefone origem')),
                ('message_text', models.TextField(blank=True, verbose_name='texto da mensagem')),
                ('response_text', models.TextField(blank=True, verbose_name='texto da resposta')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('canal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='webhook_logs', to='whatsapp_api.canalwhatsapp', verbose_name='canal')),
            ],
            options={
                'verbose_name': 'log de webhook',
                'verbose_name_plural': 'logs de webhook',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='webhooklog',
            index=models.Index(fields=['canal', 'event_type'], name='whatsapp_ap_canal_i_f22c0c_idx'),
        ),
        migrations.AddIndex(
            model_name='webhooklog',
            index=models.Index(fields=['created_at'], name='whatsapp_ap_created_b77f29_idx'),
        ),
        migrations.AddIndex(
            model_name='webhooklog',
            index=models.Index(fields=['processed'], name='whatsapp_ap_process_d5e917_idx'),
        ),
        migrations.AddIndex(
            model_name='canalwhatsapp',
            index=models.Index(fields=['contabilidade', 'is_active'], name='whatsapp_ap_contabi_f1b1d1_idx'),
        ),
        migrations.AddIndex(
            model_name='canalwhatsapp',
            index=models.Index(fields=['instance_name'], name='whatsapp_ap_instanc_35adc1_idx'),
        ),
    ]
