# Generated by Django 4.1.11 on 2026-02-12 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvolutionChat',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('instance_id', models.CharField(db_column='instanceId', max_length=255)),
                ('remote_jid', models.CharField(db_column='remoteJid', max_length=255)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('labels', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, db_column='createdAt', null=True)),
                ('updated_at', models.DateTimeField(blank=True, db_column='updatedAt', null=True)),
            ],
            options={
                'verbose_name': 'Chat Evolution',
                'verbose_name_plural': 'Chats Evolution',
                'db_table': 'Chat',
                'ordering': ['-updated_at'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EvolutionContact',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('instance_id', models.CharField(db_column='instanceId', max_length=255)),
                ('remote_jid', models.CharField(db_column='remoteJid', max_length=255)),
                ('push_name', models.CharField(blank=True, db_column='pushName', max_length=255, null=True)),
                ('profile_pic_url', models.TextField(blank=True, db_column='profilePicUrl', null=True)),
                ('created_at', models.DateTimeField(blank=True, db_column='createdAt', null=True)),
                ('updated_at', models.DateTimeField(blank=True, db_column='updatedAt', null=True)),
            ],
            options={
                'verbose_name': 'Contato Evolution',
                'verbose_name_plural': 'Contatos Evolution',
                'db_table': 'Contact',
                'ordering': ['push_name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EvolutionInstance',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('connection_status', models.CharField(db_column='connectionStatus', max_length=50)),
                ('owner_jid', models.CharField(blank=True, db_column='ownerJid', max_length=100, null=True)),
                ('profile_name', models.CharField(blank=True, db_column='profileName', max_length=255, null=True)),
                ('profile_pic_url', models.TextField(blank=True, db_column='profilePicUrl', null=True)),
                ('integration', models.CharField(blank=True, max_length=50, null=True)),
                ('number', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(blank=True, db_column='createdAt', null=True)),
                ('updated_at', models.DateTimeField(blank=True, db_column='updatedAt', null=True)),
            ],
            options={
                'verbose_name': 'Instância Evolution',
                'verbose_name_plural': 'Instâncias Evolution',
                'db_table': 'Instance',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EvolutionMessage',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('instance_id', models.TextField(db_column='instanceId')),
                ('key', models.JSONField()),
                ('push_name', models.CharField(blank=True, db_column='pushName', max_length=255, null=True)),
                ('participant', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.JSONField(blank=True, null=True)),
                ('message_type', models.CharField(blank=True, db_column='messageType', max_length=50, null=True)),
                ('context_info', models.JSONField(blank=True, db_column='contextInfo', null=True)),
                ('source', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('session_id', models.TextField(blank=True, db_column='sessionId', null=True)),
                ('message_timestamp', models.BigIntegerField(blank=True, db_column='messageTimestamp', null=True)),
            ],
            options={
                'verbose_name': 'Mensagem Evolution',
                'verbose_name_plural': 'Mensagens Evolution',
                'db_table': 'Message',
                'ordering': ['-message_timestamp'],
                'managed': False,
            },
        ),
    ]
