# Generated by Django 4.1.11 on 2026-01-21 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SessionMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Usuário'), ('assistant', 'Assistente'), ('system', 'Sistema')], max_length=10, verbose_name='Papel')),
                ('content', models.TextField(verbose_name='Conteúdo')),
                ('timestamp', models.DateTimeField(verbose_name='Data/Hora')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Mensagem',
                'verbose_name_plural': 'Mensagens',
                'ordering': ['session', 'order', 'timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SessionSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessao_id', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='ID da Sessão')),
                ('telefone', models.CharField(db_index=True, max_length=20, verbose_name='Telefone')),
                ('estado', models.CharField(choices=[('coleta', 'Coletando Dados'), ('dados_incompletos', 'Dados Incompletos'), ('dados_completos', 'Dados Completos'), ('aguardando_confirmacao', 'Aguardando Confirmação'), ('processando', 'Processando'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado'), ('erro', 'Erro'), ('cancelado_usuario', 'Cancelado pelo Usuário'), ('expirado', 'Expirado')], db_index=True, default='coleta', max_length=25, verbose_name='Estado')),
                ('cnpj_status', models.CharField(choices=[('validated', 'Validado'), ('null', 'Não Informado'), ('error', 'Erro'), ('warning', 'Atenção')], default='null', max_length=10, verbose_name='Status CNPJ')),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True, verbose_name='CNPJ')),
                ('cnpj_razao_social', models.CharField(blank=True, max_length=200, null=True, verbose_name='Razão Social')),
                ('cnpj_issue', models.TextField(blank=True, null=True, verbose_name='Problema CNPJ')),
                ('valor_status', models.CharField(choices=[('validated', 'Validado'), ('null', 'Não Informado'), ('error', 'Erro'), ('warning', 'Atenção')], default='null', max_length=10, verbose_name='Status Valor')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor')),
                ('valor_formatted', models.CharField(blank=True, max_length=30, null=True, verbose_name='Valor Formatado')),
                ('valor_issue', models.TextField(blank=True, null=True, verbose_name='Problema Valor')),
                ('descricao_status', models.CharField(choices=[('validated', 'Validado'), ('null', 'Não Informado'), ('error', 'Erro'), ('warning', 'Atenção')], default='null', max_length=10, verbose_name='Status Descrição')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('descricao_issue', models.TextField(blank=True, null=True, verbose_name='Problema Descrição')),
                ('data_complete', models.BooleanField(default=False, verbose_name='Dados Completos')),
                ('missing_fields', models.JSONField(blank=True, default=list, verbose_name='Campos Faltantes')),
                ('invalid_fields', models.JSONField(blank=True, default=list, verbose_name='Campos Inválidos')),
                ('interaction_count', models.PositiveIntegerField(default=0, verbose_name='Total Interações')),
                ('bot_message_count', models.PositiveIntegerField(default=0, verbose_name='Mensagens Bot')),
                ('ai_calls_count', models.PositiveIntegerField(default=0, verbose_name='Chamadas IA')),
                ('session_created_at', models.DateTimeField(verbose_name='Sessão Criada Em')),
                ('session_updated_at', models.DateTimeField(verbose_name='Sessão Atualizada Em')),
                ('snapshot_created_at', models.DateTimeField(auto_now_add=True, verbose_name='Snapshot Criado Em')),
                ('snapshot_reason', models.CharField(choices=[('data_complete', 'Dados Completos'), ('confirmed', 'Confirmado pelo Usuário'), ('cancelled', 'Cancelado pelo Usuário'), ('expired', 'Sessão Expirada'), ('error', 'Erro na Sessão'), ('manual', 'Salvo Manualmente')], default='manual', max_length=20, verbose_name='Motivo do Snapshot')),
            ],
            options={
                'verbose_name': 'Sessão Persistida',
                'verbose_name_plural': 'Sessões Persistidas',
                'ordering': ['-session_created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='sessionsnapshot',
            index=models.Index(fields=['telefone', 'estado'], name='core_sessio_telefon_6783f1_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionsnapshot',
            index=models.Index(fields=['data_complete'], name='core_sessio_data_co_dbff61_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionsnapshot',
            index=models.Index(fields=['session_created_at'], name='core_sessio_session_6c4e56_idx'),
        ),
        migrations.AddField(
            model_name='sessionmessage',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.sessionsnapshot', verbose_name='Sessão'),
        ),
        migrations.AddIndex(
            model_name='sessionmessage',
            index=models.Index(fields=['session', 'timestamp'], name='core_sessio_session_d3db2b_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionmessage',
            index=models.Index(fields=['role'], name='core_sessio_role_0d73bc_idx'),
        ),
    ]
