# Generated by Django 5.2.9 on 2026-01-28 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SessionSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessao_id', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='ID da Sessão')),
                ('telefone', models.CharField(db_index=True, max_length=20, verbose_name='Telefone')),
                ('usuario_nome', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome do Usuário')),
                ('empresa_nome', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome da Empresa')),
                ('empresa_id', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='ID da Empresa')),
                ('estado', models.CharField(choices=[('coleta', 'Coletando Dados'), ('dados_incompletos', 'Dados Incompletos'), ('aguardando_confirmacao', 'Aguardando Confirmação'), ('processando', 'Processando'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado'), ('erro', 'Erro'), ('cancelado_usuario', 'Cancelado pelo Usuário'), ('expirado', 'Expirado')], db_index=True, default='coleta', max_length=25, verbose_name='Estado')),
                ('cnpj_status', models.CharField(choices=[('validated', 'Validado'), ('null', 'Não Informado'), ('error', 'Erro'), ('warning', 'Atenção')], default='null', max_length=10, verbose_name='Status CNPJ')),
                ('cnpj_extracted', models.CharField(blank=True, max_length=30, null=True, verbose_name='CNPJ Extraído')),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True, verbose_name='CNPJ')),
                ('cnpj_razao_social', models.CharField(blank=True, max_length=200, null=True, verbose_name='Razão Social')),
                ('cnpj_issue', models.TextField(blank=True, null=True, verbose_name='Problema CNPJ')),
                ('cnpj_error_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo Erro CNPJ')),
                ('valor_status', models.CharField(choices=[('validated', 'Validado'), ('null', 'Não Informado'), ('error', 'Erro'), ('warning', 'Atenção')], default='null', max_length=10, verbose_name='Status Valor')),
                ('valor_extracted', models.CharField(blank=True, max_length=50, null=True, verbose_name='Valor Extraído')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor')),
                ('valor_formatted', models.CharField(blank=True, max_length=30, null=True, verbose_name='Valor Formatado')),
                ('valor_issue', models.TextField(blank=True, null=True, verbose_name='Problema Valor')),
                ('valor_error_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo Erro Valor')),
                ('descricao_status', models.CharField(choices=[('validated', 'Validado'), ('null', 'Não Informado'), ('error', 'Erro'), ('warning', 'Atenção')], default='null', max_length=10, verbose_name='Status Descrição')),
                ('descricao_extracted', models.TextField(blank=True, null=True, verbose_name='Descrição Extraída')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('descricao_issue', models.TextField(blank=True, null=True, verbose_name='Problema Descrição')),
                ('descricao_error_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo Erro Descrição')),
                ('data_complete', models.BooleanField(default=False, verbose_name='Dados Completos')),
                ('missing_fields', models.JSONField(blank=True, default=list, verbose_name='Campos Faltantes')),
                ('invalid_fields', models.JSONField(blank=True, default=list, verbose_name='Campos Inválidos')),
                ('user_message', models.TextField(blank=True, null=True, verbose_name='Mensagem ao Usuário')),
                ('id_integracao', models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True, verbose_name='ID Integração NFSe')),
                ('ttl', models.PositiveIntegerField(default=3600, verbose_name='TTL (segundos)')),
                ('interaction_count', models.PositiveIntegerField(default=0, verbose_name='Total Interações')),
                ('bot_message_count', models.PositiveIntegerField(default=0, verbose_name='Mensagens Bot')),
                ('ai_calls_count', models.PositiveIntegerField(default=0, verbose_name='Chamadas IA')),
                ('session_created_at', models.DateTimeField(verbose_name='Sessão Criada Em')),
                ('session_updated_at', models.DateTimeField(verbose_name='Sessão Atualizada Em')),
                ('snapshot_created_at', models.DateTimeField(auto_now_add=True, verbose_name='Snapshot Criado Em')),
                ('snapshot_reason', models.CharField(choices=[('data_complete', 'Dados Completos'), ('confirmed', 'Confirmado pelo Usuário'), ('cancelled', 'Cancelado pelo Usuário'), ('expired', 'Sessão Expirada'), ('error', 'Erro na Sessão'), ('manual', 'Salvo Manualmente')], default='manual', max_length=20, verbose_name='Motivo do Snapshot')),
            ],
            options={
                'verbose_name': 'Sessão Persistida',
                'verbose_name_plural': 'Sessões Persistidas',
                'ordering': ['-session_created_at'],
                'indexes': [models.Index(fields=['telefone', 'estado'], name='core_sessio_telefon_6783f1_idx'), models.Index(fields=['data_complete'], name='core_sessio_data_co_dbff61_idx'), models.Index(fields=['session_created_at'], name='core_sessio_session_6c4e56_idx'), models.Index(fields=['telefone', '-session_updated_at'], name='core_sessio_telefon_f0cc64_idx')],
            },
        ),
        migrations.CreateModel(
            name='SessionMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Usuário'), ('assistant', 'Assistente'), ('system', 'Sistema')], max_length=10, verbose_name='Papel')),
                ('content', models.TextField(verbose_name='Conteúdo')),
                ('timestamp', models.DateTimeField(verbose_name='Data/Hora')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.sessionsnapshot', verbose_name='Sessão')),
            ],
            options={
                'verbose_name': 'Mensagem',
                'verbose_name_plural': 'Mensagens',
                'ordering': ['session', 'order', 'timestamp'],
                'indexes': [models.Index(fields=['session', 'timestamp'], name='core_sessio_session_d3db2b_idx'), models.Index(fields=['role'], name='core_sessio_role_0d73bc_idx')],
            },
        ),
    ]
