# Generated by Django 5.2.9 on 2026-02-13 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionsnapshot',
            name='pending_suggestion',
            field=models.JSONField(blank=True, null=True, verbose_name='Sugestao Pendente'),
        ),
    ]
