# Generated by Django 4.1.11 on 2026-01-21 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_session_persistence'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionsnapshot',
            name='cnpj_error_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo Erro CNPJ'),
        ),
        migrations.AddField(
            model_name='sessionsnapshot',
            name='cnpj_extracted',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='CNPJ Extraído'),
        ),
        migrations.AddField(
            model_name='sessionsnapshot',
            name='descricao_error_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo Erro Descrição'),
        ),
        migrations.AddField(
            model_name='sessionsnapshot',
            name='descricao_extracted',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição Extraída'),
        ),
        migrations.AddField(
            model_name='sessionsnapshot',
            name='ttl',
            field=models.PositiveIntegerField(default=3600, verbose_name='TTL (segundos)'),
        ),
        migrations.AddField(
            model_name='sessionsnapshot',
            name='user_message',
            field=models.TextField(blank=True, null=True, verbose_name='Mensagem ao Usuário'),
        ),
        migrations.AddField(
            model_name='sessionsnapshot',
            name='valor_error_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo Erro Valor'),
        ),
        migrations.AddField(
            model_name='sessionsnapshot',
            name='valor_extracted',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Valor Extraído'),
        ),
        migrations.AddIndex(
            model_name='sessionsnapshot',
            index=models.Index(fields=['telefone', '-session_updated_at'], name='core_sessio_telefon_f0cc64_idx'),
        ),
    ]
