# Generated by Django 5.2.9 on 2026-01-24 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_session_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionsnapshot',
            name='id_integracao',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True, verbose_name='ID Integração NFSe'),
        ),
    ]
