# Generated by Django 5.2.9 on 2026-01-25 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sessionsnapshot_id_integracao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionsnapshot',
            name='estado',
            field=models.CharField(choices=[('coleta', 'Coletando Dados'), ('dados_incompletos', 'Dados Incompletos'), ('aguardando_confirmacao', 'Aguardando Confirmação'), ('processando', 'Processando'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado'), ('erro', 'Erro'), ('cancelado_usuario', 'Cancelado pelo Usuário'), ('expirado', 'Expirado')], db_index=True, default='coleta', max_length=25, verbose_name='Estado'),
        ),
    ]
