# Generated by Django 5.2.9 on 2026-01-25 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_sessionsnapshot_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionsnapshot',
            name='empresa_id_snapshot',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='ID da Empresa (Snapshot)'),
        ),
        migrations.AddField(
            model_name='sessionsnapshot',
            name='empresa_nome_snapshot',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome da Empresa (Snapshot)'),
        ),
        migrations.AddField(
            model_name='sessionsnapshot',
            name='usuario_nome_snapshot',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome do Usuário (Snapshot)'),
        ),
    ]
