# Generated by Django 5.2.9 on 2026-01-25 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_sessionsnapshot_empresa_id_snapshot_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sessionsnapshot',
            old_name='usuario_nome_snapshot',
            new_name='usuario_nome',
        ),
        migrations.RenameField(
            model_name='sessionsnapshot',
            old_name='empresa_nome_snapshot',
            new_name='empresa_nome',
        ),
        migrations.RenameField(
            model_name='sessionsnapshot',
            old_name='empresa_id_snapshot',
            new_name='empresa_id',
        ),
    ]
