# Generated by Django 5.2.9 on 2026-01-28 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_snapshot_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionsnapshot',
            name='empresa_id',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='ID da Empresa'),
        ),
        migrations.AlterField(
            model_name='sessionsnapshot',
            name='empresa_nome',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome da Empresa'),
        ),
        migrations.AlterField(
            model_name='sessionsnapshot',
            name='usuario_nome',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome do Usuário'),
        ),
    ]
