# Generated by Django 5.2.9 on 2026-01-28 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contabilidade', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteTomador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(db_index=True, max_length=14, unique=True, verbose_name='CNPJ')),
                ('razao_social', models.CharField(max_length=255, verbose_name='Razão Social')),
                ('nome_fantasia', models.CharField(blank=True, max_length=255, verbose_name='Nome Fantasia')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('inscricao_municipal', models.CharField(blank=True, max_length=20, verbose_name='Inscrição Municipal')),
                ('inscricao_estadual', models.CharField(blank=True, max_length=20, verbose_name='Inscrição Estadual')),
                ('cep', models.CharField(max_length=8, verbose_name='CEP')),
                ('logradouro', models.CharField(max_length=255, verbose_name='Logradouro')),
                ('numero', models.CharField(max_length=10, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=100, verbose_name='Complemento')),
                ('bairro', models.CharField(max_length=100, verbose_name='Bairro')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('codigo_cidade', models.CharField(max_length=7, verbose_name='Código IBGE')),
                ('estado', models.CharField(max_length=2, verbose_name='UF')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('dados_receita_raw', models.JSONField(blank=True, null=True, verbose_name='Dados Brutos Receita')),
            ],
            options={
                'verbose_name': 'Cliente Tomador',
                'verbose_name_plural': 'Clientes Tomadores',
                'ordering': ['razao_social'],
            },
        ),
        migrations.CreateModel(
            name='NFSeEmissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_integracao', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='ID Integração')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('enviado', 'Enviado'), ('processando', 'Processando'), ('concluido', 'Concluído'), ('erro', 'Erro'), ('cancelado', 'Cancelado')], default='pendente', max_length=20, verbose_name='Status')),
                ('codigo_servico', models.CharField(default='14.10', max_length=10, verbose_name='Código Serviço')),
                ('codigo_tributacao', models.CharField(default='14.10', max_length=10, verbose_name='Código Tributação')),
                ('descricao_servico', models.TextField(verbose_name='Descrição do Serviço')),
                ('cnae', models.CharField(default='7490104', max_length=10, verbose_name='CNAE')),
                ('valor_servico', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor do Serviço')),
                ('desconto_condicionado', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Desconto Condicionado')),
                ('desconto_incondicionado', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Desconto Incondicionado')),
                ('tipo_tributacao', models.IntegerField(default=7, verbose_name='Tipo Tributação')),
                ('exigibilidade', models.IntegerField(default=1, verbose_name='Exigibilidade')),
                ('aliquota', models.DecimalField(decimal_places=2, default=3, max_digits=5, verbose_name='Alíquota ISS (%)')),
                ('payload_enviado', models.JSONField(blank=True, null=True, verbose_name='Payload Enviado')),
                ('resposta_gateway', models.JSONField(blank=True, null=True, verbose_name='Resposta Gateway')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('enviado_em', models.DateTimeField(blank=True, null=True, verbose_name='Enviado em')),
                ('processado_em', models.DateTimeField(blank=True, null=True, verbose_name='Processado em')),
                ('erro_mensagem', models.TextField(blank=True, verbose_name='Mensagem de Erro')),
                ('prestador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nfse_emitidas', to='contabilidade.empresa', verbose_name='Prestador')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nfse_emissoes', to='core.sessionsnapshot', verbose_name='Sessão')),
                ('tomador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nfse_recebidas', to='nfse.clientetomador', verbose_name='Tomador')),
            ],
            options={
                'verbose_name': 'Emissão NFSe',
                'verbose_name_plural': 'Emissões NFSe',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NFSeProcessada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_externo', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='ID Externo')),
                ('numero', models.CharField(max_length=20, verbose_name='Número')),
                ('serie', models.CharField(blank=True, max_length=10, verbose_name='Série')),
                ('chave', models.CharField(max_length=100, unique=True, verbose_name='Chave')),
                ('protocolo', models.CharField(max_length=50, verbose_name='Protocolo')),
                ('status', models.CharField(max_length=50, verbose_name='Status')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
                ('c_stat', models.IntegerField(verbose_name='Código Status Fiscal')),
                ('emitente', models.CharField(max_length=14, verbose_name='CNPJ Emitente')),
                ('destinatario', models.CharField(max_length=14, verbose_name='CNPJ/CPF Destinatário')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor')),
                ('data_emissao', models.DateField(verbose_name='Data Emissão')),
                ('data_autorizacao', models.DateField(verbose_name='Data Autorização')),
                ('url_xml', models.URLField(blank=True, max_length=500, verbose_name='URL XML')),
                ('url_pdf', models.URLField(blank=True, max_length=500, verbose_name='URL PDF')),
                ('destinada', models.BooleanField(default=False, verbose_name='Destinada')),
                ('documento', models.CharField(default='nfse', max_length=20, verbose_name='Tipo Documento')),
                ('webhook_payload', models.JSONField(verbose_name='Payload Webhook')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('emissao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nota_processada', to='nfse.nfseemissao', verbose_name='Emissão')),
            ],
            options={
                'verbose_name': 'NFSe Processada',
                'verbose_name_plural': 'NFSes Processadas',
                'ordering': ['-data_emissao', '-numero'],
            },
        ),
        migrations.CreateModel(
            name='EmpresaClienteTomador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primeira_nota_em', models.DateTimeField(auto_now_add=True, help_text='Data da primeira nota emitida pela empresa para este cliente', verbose_name='Primeira Nota Emitida em')),
                ('ultima_nota_em', models.DateTimeField(auto_now=True, help_text='Data da última nota emitida pela empresa para este cliente', verbose_name='Última Nota Emitida em')),
                ('is_active', models.BooleanField(default=True, help_text='Indica se a empresa ainda trabalha com este cliente', verbose_name='Relacionamento Ativo')),
                ('apelido', models.CharField(blank=True, help_text='Nome customizado que a empresa usa internamente para este cliente', max_length=100, verbose_name='Apelido do Cliente')),
                ('observacoes', models.TextField(blank=True, help_text='Anotações da empresa sobre este cliente', verbose_name='Observações Internas')),
                ('cliente_tomador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='empresas_vinculadas', to='nfse.clientetomador', verbose_name='Cliente Tomador')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes_tomadores_vinculados', to='contabilidade.empresa', verbose_name='Empresa Prestadora')),
            ],
            options={
                'verbose_name': 'Empresa-Cliente Tomador',
                'verbose_name_plural': 'Empresas-Clientes Tomadores',
                'ordering': ['-ultima_nota_em'],
                'indexes': [models.Index(fields=['empresa', 'cliente_tomador'], name='nfse_empres_empresa_40c80a_idx'), models.Index(fields=['empresa', 'is_active'], name='nfse_empres_empresa_25bfa2_idx'), models.Index(fields=['-ultima_nota_em'], name='nfse_empres_ultima__539484_idx')],
                'unique_together': {('empresa', 'cliente_tomador')},
            },
        ),
    ]
