# Generated by Django 5.2.9 on 2026-01-28 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidade', '0001_initial'),
        ('nfse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresaClienteTomador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primeira_nota_em', models.DateTimeField(auto_now_add=True, help_text='Data da primeira nota emitida pela empresa para este cliente', verbose_name='Primeira Nota Emitida em')),
                ('ultima_nota_em', models.DateTimeField(auto_now=True, help_text='Data da última nota emitida pela empresa para este cliente', verbose_name='Última Nota Emitida em')),
                ('is_active', models.BooleanField(default=True, help_text='Indica se a empresa ainda trabalha com este cliente', verbose_name='Relacionamento Ativo')),
                ('apelido', models.CharField(blank=True, help_text='Nome customizado que a empresa usa internamente para este cliente', max_length=100, verbose_name='Apelido do Cliente')),
                ('observacoes', models.TextField(blank=True, help_text='Anotações da empresa sobre este cliente', verbose_name='Observações Internas')),
                ('cliente_tomador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='empresas_vinculadas', to='nfse.clientetomador', verbose_name='Cliente Tomador')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes_tomadores_vinculados', to='contabilidade.empresa', verbose_name='Empresa Prestadora')),
            ],
            options={
                'verbose_name': 'Empresa-Cliente Tomador',
                'verbose_name_plural': 'Empresas-Clientes Tomadores',
                'ordering': ['-ultima_nota_em'],
                'indexes': [models.Index(fields=['empresa', 'cliente_tomador'], name='nfse_empres_empresa_40c80a_idx'), models.Index(fields=['empresa', 'is_active'], name='nfse_empres_empresa_25bfa2_idx'), models.Index(fields=['-ultima_nota_em'], name='nfse_empres_ultima__539484_idx')],
                'unique_together': {('empresa', 'cliente_tomador')},
            },
        ),
    ]
