# Generated by Django 5.2.9 on 2026-02-13 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidade', '0004_cnae_com_descricao'),
        ('core', '0002_sessionsnapshot_pending_suggestion'),
        ('nfse', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='nfseemissao',
            index=models.Index(fields=['prestador', '-created_at'], name='idx_emissao_prestador_data'),
        ),
        migrations.AddIndex(
            model_name='nfseemissao',
            index=models.Index(fields=['prestador', 'tomador', '-created_at'], name='idx_emissao_prest_tom_data'),
        ),
    ]
