# Generated by Django 5.2.9 on 2026-01-28 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contabilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=18, unique=True, verbose_name='CNPJ')),
                ('razao_social', models.CharField(max_length=200, verbose_name='razão social')),
                ('nome_fantasia', models.CharField(blank=True, max_length=200, verbose_name='nome fantasia')),
                ('email', models.EmailField(max_length=254, verbose_name='e-mail')),
                ('telefone_ddd', models.CharField(blank=True, max_length=2, verbose_name='DDD')),
                ('telefone_numero', models.CharField(blank=True, max_length=15, verbose_name='telefone')),
                ('cep', models.CharField(blank=True, max_length=9, verbose_name='CEP')),
                ('logradouro', models.CharField(blank=True, max_length=200, verbose_name='logradouro')),
                ('numero', models.CharField(blank=True, max_length=20, verbose_name='número')),
                ('complemento', models.CharField(blank=True, max_length=100, verbose_name='complemento')),
                ('bairro', models.CharField(blank=True, max_length=100, verbose_name='bairro')),
                ('cidade', models.CharField(blank=True, max_length=100, verbose_name='cidade')),
                ('estado', models.CharField(blank=True, max_length=2, verbose_name='estado')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
            ],
            options={
                'verbose_name': 'contabilidade',
                'verbose_name_plural': 'contabilidades',
                'ordering': ['razao_social'],
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf_cnpj', models.CharField(max_length=18, verbose_name='CPF/CNPJ')),
                ('razao_social', models.CharField(max_length=200, verbose_name='razão social')),
                ('nome_fantasia', models.CharField(blank=True, max_length=200, verbose_name='nome fantasia')),
                ('inscricao_municipal', models.CharField(blank=True, max_length=20, verbose_name='inscrição municipal')),
                ('inscricao_estadual', models.CharField(blank=True, max_length=20, verbose_name='inscrição estadual')),
                ('simples_nacional', models.BooleanField(default=False, verbose_name='Simples Nacional')),
                ('regime_tributario', models.IntegerField(choices=[(1, 'Simples Nacional'), (2, 'Simples Nacional - Excesso'), (3, 'Regime Normal')], default=3, verbose_name='regime tributário')),
                ('incentivo_fiscal', models.BooleanField(default=False, verbose_name='incentivo fiscal')),
                ('incentivador_cultural', models.BooleanField(default=False, verbose_name='incentivador cultural')),
                ('regime_tributario_especial', models.IntegerField(choices=[(0, 'Nenhum'), (1, 'Microempresa Municipal'), (2, 'Estimativa'), (3, 'Sociedade de Profissionais'), (4, 'Cooperativa'), (5, 'MEI'), (6, 'ME/EPP')], default=0, verbose_name='regime tributário especial')),
                ('cep', models.CharField(blank=True, max_length=9, verbose_name='CEP')),
                ('logradouro', models.CharField(blank=True, max_length=200, verbose_name='logradouro')),
                ('numero', models.CharField(blank=True, max_length=20, verbose_name='número')),
                ('complemento', models.CharField(blank=True, max_length=100, verbose_name='complemento')),
                ('bairro', models.CharField(blank=True, max_length=100, verbose_name='bairro')),
                ('tipo_logradouro', models.CharField(blank=True, max_length=50, verbose_name='tipo logradouro')),
                ('tipo_bairro', models.CharField(blank=True, max_length=50, verbose_name='tipo bairro')),
                ('codigo_cidade', models.CharField(blank=True, max_length=7, verbose_name='código cidade (IBGE)')),
                ('descricao_cidade', models.CharField(blank=True, max_length=100, verbose_name='cidade')),
                ('estado', models.CharField(blank=True, max_length=2, verbose_name='estado')),
                ('codigo_pais', models.CharField(default='1058', max_length=4, verbose_name='código país')),
                ('descricao_pais', models.CharField(default='Brasil', max_length=100, verbose_name='país')),
                ('telefone_ddd', models.CharField(blank=True, max_length=2, verbose_name='DDD')),
                ('telefone_numero', models.CharField(blank=True, max_length=15, verbose_name='telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('nfse_ativo', models.BooleanField(default=True, verbose_name='NFSe ativo')),
                ('nfse_producao', models.BooleanField(default=False, verbose_name='ambiente produção')),
                ('tecnospeed_id', models.CharField(blank=True, help_text='ID retornado pela API Tecnospeed ao cadastrar empresa', max_length=50, verbose_name='ID empresa Tecnospeed')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('contabilidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresas', to='contabilidade.contabilidade', verbose_name='contabilidade')),
            ],
            options={
                'verbose_name': 'empresa',
                'verbose_name_plural': 'empresas',
                'ordering': ['razao_social'],
            },
        ),
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(help_text='Arquivo do certificado digital no formato .pfx', upload_to='certificados/', verbose_name='arquivo (.pfx)')),
                ('senha', models.CharField(help_text='Senha do certificado (armazenada de forma segura)', max_length=100, verbose_name='senha')),
                ('nome_titular', models.CharField(blank=True, max_length=200, verbose_name='nome titular')),
                ('cnpj_titular', models.CharField(blank=True, max_length=18, verbose_name='CNPJ titular')),
                ('validade', models.DateField(blank=True, null=True, verbose_name='data validade')),
                ('tecnospeed_id', models.CharField(blank=True, help_text='ID retornado ao enviar para Tecnospeed', max_length=50, verbose_name='ID Tecnospeed')),
                ('enviado_tecnospeed', models.BooleanField(default=False, verbose_name='enviado para Tecnospeed')),
                ('data_envio_tecnospeed', models.DateTimeField(blank=True, null=True, verbose_name='data envio Tecnospeed')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificados', to='contabilidade.empresa', verbose_name='empresa')),
            ],
            options={
                'verbose_name': 'certificado digital',
                'verbose_name_plural': 'certificados digitais',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UsuarioEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='nome')),
                ('cpf', models.CharField(blank=True, max_length=14, verbose_name='CPF')),
                ('telefone', models.CharField(max_length=20, verbose_name='telefone (WhatsApp)')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('cep', models.CharField(blank=True, max_length=9, verbose_name='CEP')),
                ('logradouro', models.CharField(blank=True, max_length=200, verbose_name='logradouro')),
                ('numero', models.CharField(blank=True, max_length=20, verbose_name='número')),
                ('complemento', models.CharField(blank=True, max_length=100, verbose_name='complemento')),
                ('bairro', models.CharField(blank=True, max_length=100, verbose_name='bairro')),
                ('cidade', models.CharField(blank=True, max_length=100, verbose_name='cidade')),
                ('estado', models.CharField(blank=True, max_length=2, verbose_name='estado')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_autorizados', to='contabilidade.empresa', verbose_name='empresa')),
            ],
            options={
                'verbose_name': 'usuário da empresa',
                'verbose_name_plural': 'usuários da empresa',
                'ordering': ['nome'],
            },
        ),
        migrations.AddIndex(
            model_name='empresa',
            index=models.Index(fields=['contabilidade', 'cpf_cnpj'], name='contabilida_contabi_16a7fe_idx'),
        ),
        migrations.AddIndex(
            model_name='empresa',
            index=models.Index(fields=['contabilidade', 'is_active'], name='contabilida_contabi_d0e7f0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='empresa',
            unique_together={('contabilidade', 'cpf_cnpj')},
        ),
        migrations.AddConstraint(
            model_name='usuarioempresa',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('telefone',), name='unique_telefone_ativo', violation_error_message='Este telefone já está cadastrado em outra empresa ativa.'),
        ),
    ]
