# Generated by Django 5.2.9 on 2026-01-28 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidade', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='cnae_principal',
            field=models.CharField(blank=True, max_length=10, verbose_name='CNAE principal'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='cnae_secundarios',
            field=models.TextField(blank=True, help_text='Separados por vírgula', verbose_name='CNAEs secundários'),
        ),
    ]
