# Generated by Django 5.2.9 on 2026-01-28 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidade', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usuarioempresa',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='usuarioempresa',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('telefone',), name='unique_telefone_ativo', violation_error_message='Este telefone já está cadastrado em outra empresa ativa.'),
        ),
    ]
