# Generated by Django 4.1.11 on 2026-02-12 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidade', '0002_add_cnae_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='contabilidade',
            name='logotipo',
            field=models.ImageField(blank=True, help_text='Imagem PNG ou JPG, máximo 2MB', null=True, upload_to='contabilidades/logos/', verbose_name='logotipo'),
        ),
    ]
