# Generated by Django 4.1.11 on 2026-02-12 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidade', '0003_contabilidade_logotipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='cnae_principal',
            field=models.CharField(blank=True, help_text='Ex: 62.04-0-00 - Consultoria em tecnologia da informação', max_length=255, verbose_name='CNAE principal'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='cnae_secundarios',
            field=models.TextField(blank=True, help_text='Um CNAE por linha com código e descrição', verbose_name='CNAEs secundários'),
        ),
    ]
